### ISSUE TITLE
Basic Token creation page

### ISSUE THREAD

**Issue by NutellaLicka** [TokelPlatform/tokel_dapp#100]
These are the basic input fields the token creation page should have in it. Maybe we can get sexy with it at a later date, but this will be the minimum required.

### Input fields
- Name (max 32 characters)
- Description (max description length 4096 characters)
- Total Token Supply: (1 = NFT. >1 = fixed supply token) [The app needs to convert this number into satoshis. 1 satoshi of TKL = 1 token.]

// The below is saved in tokendata part of the token, see docs for reference
- ID: [arbitrary ID number, could be used for bundles within the application/ marketplace exploration]
- Url: [any string, needs to accept IPFS hashes]
- Royalty (x/1000)
- Arbitrary

#### Option field, followed by input fields based on the option selected 
Do you want to add properties or arbitrary data to your token? (selectable option. either or, that creates a different input box(s))
Properties: A key & value option, with an 'add more' for as many type/value they want. (this then gets converted to HEX by the application and put into the 'arbitrary data' part of the token data)

Arbitrary data: Json format for the user to input key-value options. We can allow any format input but have to be very careful with that. The app should then convert that to HEX and add it to the 'arbitrary data' part of the token data.

### Ipfs upload
In the future we want to use https://www.ethoprotocol.com/.
For now just advice users to use a gateway to upload their token. Maybe we can give them a little guide on how to find gateways and how to choose them etc. aka  Please pick permanent solution, preferably decentralized. 

### References

Docs - https://docs.tokel.io/api/tokens/#tokenv2createtokel
TKLTEST explorer - http://explorer.komodoplatform.com:20000/TKLTEST

Some random tokens on TKLTEST: 

http://explorer.komodoplatform.com:20000/tokens/56555d676c7de8d31293bf0bb6bcfe34cddbf98e23a92d11d919f15ddd2a362c/transactions/TKLTEST

http://explorer.komodoplatform.com:20000/tokens/f756562e3832e49b29c65ce487c9809a385bdec64fc142ac6b184f3a3ab03ba9/transactions/TKLTEST

### Notes

All bitgo calls go into `src/electron/worker` file. Bitgo has native dependencies so it cant be loaded within the main or renderer process coz it blocks it, so we have to initialize it in a separate worker process.

**Comment by lenilsonjr** [comment]
Figma Prototype:

https://www.figma.com/proto/KHt6RPqitWphkuchA8vo0I/TOKEL-UI?node-id=4373%3A30181&scaling=min-zoom&page-id=4367%3A29424&starting-point-node-id=4367%3A29436&show-proto-sidebar=1
