### ISSUE TITLE
Add an option for users to find their pubkey

### ISSUE THREAD

**Issue by NutellaLicka** [TokelPlatform/tokel_dapp#132]
We need a way for users to find and copy their pubkey as this is a critical function for sending tokens. Using `tokenv2transfer` & `tokenv2transfermany` you must have the intended recipients pubkey. You cannot use their `Rxyz` address. 

A simple, 'pubkey' button or text output in their wallet will be sufficient.

**Comment by piggydoughnut** [comment]
We will just make the Receive window show pubkey on the token detail in the wallet widget section.
