### ISSUE TITLE
Add an indication of locked TKL funds to GUI

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#138]
- [x] communicate with dimxy on extending the algorithm in order to not use locked UTXOs for sending, now it just shows error
- [x] design 
- [x] implement design
- [x] rewrite current transaction retrieval to use blockchain only

**Comment by NutellaLicka** [comment]
Lets take this out of 'on-hold' and aim to finished this Jan/Feb next year so we can make the transaction.

**Comment by piggydoughnut** [comment]
![TransferWidget](https://user-images.githubusercontent.com/2395326/159676515-163613ef-dca1-4839-89f0-76e8c9b2bcf4.png)
