### ISSUE TITLE
Redesign how we output coin & token addresses

### ISSUE THREAD

**Issue by NutellaLicka** [TokelPlatform/tokel_dapp#163]
Creating this task so that we can look at how we output the two different types of addresses that a user has:
Coin address (to receive TKL) - RDomQ4tftJGjcHBVpAUx549jZfxtJx74r5
Token address/pubkey (to receive tokens/NFTs) - 02dd22c272504af79b220ba37c12f777596eff4f54598e2db65be325a9393a3a26

It needs to be clear that these are two different addresses. You cannot send a token to a coin address or vice versa.

I suggest a specific area where both addresses are displayed and they can click a button to copy either or, rather than having to go into each wallet and click 'receive' to find their address.

**Comment by piggydoughnut** [comment]
We can make a new widget instead of history widget (which will move) which will show user's TKL address and their pubkey. It can look something like this.

I made a task for this here  https://github.com/TokelPlatform/tokel_dapp/issues/268
