### ISSUE TITLE
NFT image loading issues

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#173]
## Operation System

v1.1.1 on Windows

## Expected Behavior

NFT image loaded

## Current Behavior

Image is loading infinitely. Spinner is spinning.

## Steps to Reproduce

Open token detail with ipfs as an image link

**Comment by lenilsonjr** [comment]
I can imagine this has to do with the IPFS node not connecting for some reason. Do we have debug information from someone having this problem?

**Comment by piggydoughnut** [comment]
Yeah, I thought so too. 

I dont think we do, we dont really have a good logging system setup. We have log function from electron-log, but not centralized solution. Would be good to connect all console.logs to the logging function. @lenilsonjr

**Comment by lenilsonjr** [comment]
Addressing #199 should solve this bug.
