### ISSUE TITLE
V1.1.3 - Coin transaction history not outputing 'to' address

### ISSUE THREAD

**Issue by NutellaLicka** [TokelPlatform/tokel_dapp#195]
## Operation System
Windows 10

## Expected Behavior
The recipient address should be output in the transaction history page for coin transaction history.

## Current Behavior
Outputs 'This information is currently not available'. I suspect this is looking for a pubkey and not able to find it (did you change that for token transaction history which affected the coin transaction history output as well?)

## Steps to Reproduce
Click any coin send/receive transaction history
https://i.gyazo.com/8e79846c8fda093f27404a6d029cc3e1.png
https://i.gyazo.com/41c840ad8a8297c9d2cbca330913c67b.png

**Comment by piggydoughnut** [comment]
I misspelled `recepients` again 🤣  @NutellaLicka
