### ISSUE TITLE
Dapp fail to display deposits when mining 

### ISSUE THREAD

**Issue by quinbot420** [TokelPlatform/tokel_dapp#197]
## Operation System
mac os high sierra 10.13.6 intel

## Expected Behavior
deposits from mining should have been displayed in the dApp after mining with correct address for 24 hours ~100 TKL across multiple pools

## Current Behavior
no deposits displayed after mining for 24 hours ~100TKL two repeated java error messages displayed that reproduce many times 

## Series of Unfortunate Events

1. download dApp-successfully- generated and logged in with seed phrase-transferred pre mine funds from discord wallet to dApp- dApp showed locked pre mine funds soon after. great success!

2. ran miners to dApp receive address- minimized the GUI for couple hours upon opening error started 

3. ran miner for 24 hours checked dApp wallet and found no deposits and had many stacked error pop ups 

4. tried multiple pools verified address many error pop ups continue to haunt me when opening dApp

![image](https://user-images.githubusercontent.com/94413563/141871621-7124511c-c85d-4d9f-8a64-6670be0c3152.png)

![image](https://user-images.githubusercontent.com/94413563/141871530-d6ca5900-1a3c-47a9-961a-43e04406459d.png)

## Possible Solution (Not obligatory)
love is dah solution to all

**Comment by piggydoughnut** [comment]
Please confirm if this is still an issue in the new release 1.1.3. @quinbot420
