### ISSUE TITLE
Whitelist images by tokenid

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#200]
Show user a trust warning in the image frame and let them click something to load the image if they are okay with trusting the source.

**Comment by piggydoughnut** [comment]
Disclaimer:

"The Tokel team does not own, endorse, host or content moderate anything that is shown in the dApp. By it's nature, the dApp merely reads the media URL's that are linked within the meta data of tokens that are created on the Tokel public blockchain. Content moderation issues should be addressed with the token creator, owner, or through the web host that stores the media itself. By accepting this disclaimer, you are accepting that you have personally verified the source of the image and are happy for it to be displayed, knowing that there are no content moderators and you're taking all responsibility for viewing the media and any risks associated with that. You are accepting that anybody that participates in creating and/or shipping this open source software holds no liability for what is shown, and that the decision to proceed is completely voluntary and at your own risk. "

**Comment by NutellaLicka** [comment]
Should this be shown every single time they want to view content? Or allow for the user to select a button that says 'never ask again' for them to select?

**Comment by lenilsonjr** [comment]
> Should this be shown every single time they want to view content? Or allow for the user to select a button that says 'never ask again' for them to select?

@NutellaLicka we should offer both options imo: "View once", and "View and never ask again"

**Comment by NutellaLicka** [comment]
> 

Yes, or at least a tick box that says never ask again and lets them select it. But that would be a global option vs a single token option. Could go either way here
