### ISSUE TITLE
Adult Content Filter

### ISSUE THREAD

**Issue by DreamTrims** [TokelPlatform/tokel_dapp#219]
Could the dapp has this feature and how do we go about automating this?

**Comment by NutellaLicka** [comment]
The dApp looks at any information that is on the blockchain. It is not a content moderation service. Have a read of this issue and let me know what you think of it.

https://github.com/TokelPlatform/tokel_dapp/issues/200

**Comment by piggydoughnut** [comment]
We will not be moderating content of the chain.
