### ISSUE TITLE
NFT showing in 2 different wallets at the same time

### ISSUE THREAD

**Issue by Eilien-ILN** [TokelPlatform/tokel_dapp#221]
I created a NFT on my mac wallet and sent to a different wallet on windows. The NFT is now showing in both wallets ?

**Comment by lenilsonjr** [comment]
Hi there. Does the issue persist if you close and re-open the app with the wallet that isn't supposed to have the NFT?

**Comment by piggydoughnut** [comment]
This is being worked on as a part of #150 and #151
