### ISSUE TITLE
My NFT disappeared.

### ISSUE THREAD

**Issue by ilnatomicdex** [TokelPlatform/tokel_dapp#250]
MAC M1 MAS OS Monterey 
Link to NFT https://explorer.tokel.io/tokens/957cccc9a34285fed2f7f44abc6f01b40cd508108b0bfedda5df338111433faa/transactions 

All was good I created 2 NFT but when I sent 1 of the to a friend the other disappeared from my wallet MMM any Ideas ?

**Comment by lenilsonjr** [comment]
Hi, thanks for the bug report.

This may have been a temporary issue with node connection when fetching transactions, or related to #220.

Please reopen if the issue persists.
