### ISSUE TITLE
Token creation unnecessary fields in "arbitrary data" 

### ISSUE THREAD

**Issue by Alrighttt** [TokelPlatform/tokel_dapp#253]
If you opt not to include anything for "collection_name" or "number_in_collection" fields while creating a NFT, these fields will still be added to the "arbitrary" data field as empty entries: 

eg: 
```
{
  "url": "ipfs://QmZq4dts7tvUUagbsLU7bDDkQBfjqAtCDoMG1EPphFigtu",
  "arbitrary": "{\"collection_name\":\"\",\"number_in_collection\":\"\"}"
}
```
An example:
https://tokel.explorer.dexstats.info/tokens/cd79ce03433e0e7b9cc0c9adde647956b0faf5a6325e0dd26b7e7b0df66622a3/transactions

The "arbitrary" field should not be included at all.

**Comment by lenilsonjr** [comment]
This has been addressed in #235 and will be released soon.
