### ISSUE TITLE
Tokens and NFTs not showing in Token Wallet

### ISSUE THREAD

**Issue by kelcie33** [TokelPlatform/tokel_dapp#254]
## Expected Behavior

I should be able to see the tokens in the wallet. 

## Current Behavior

No token previews even though app says I have 3 tokens. 

## Steps to Reproduce

1.
Running dApp version 1.2.0
MacOS Big Sur 11.5.1
2.
Tokens are not showing up in token wallet. The application says that I have 3 tokens, they were visible a few days ago. I also confirmed with someone using windows that they are having the same issue 
3.

4. Screenshots of token wallet section 

![image](https://user-images.githubusercontent.com/10329007/150005189-f3cebcdb-9fa4-4144-8f0e-ee9a8d5892c9.png)

![image](https://user-images.githubusercontent.com/10329007/150005213-4b522fe6-25a9-4c16-9b4b-8ea77988f00d.png)

![image](https://user-images.githubusercontent.com/10329007/150005259-c657a8b1-0abe-416b-be19-db866c0ee416.png)
## Possible Solution (Not obligatory)

Possible that one of the newest changes to the Dapp broke the token previews?

**Comment by lenilsonjr** [comment]
Addressed in https://github.com/TokelPlatform/nspv-js/pull/15/
