### ISSUE TITLE
Change History widget to be the main widget on the Dashboard

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#267]
History widget is a pretty important part of the wallet part of the dapp so we want it to be bigger and more detailed.
Instead of where the history widget is currently we want to place a new widget which will show users their wallet TKL address and their token address as described in task https://github.com/TokelPlatform/tokel_dapp/issues/268

Since the history widget will become wider, we can add a link to the transaction in explorer and also a copy icon to copy transaction id.

<img width="1232" alt="Screenshot 2022-03-25 at 11 20 47" src="https://user-images.githubusercontent.com/2395326/160055623-b9fa6f92-ff9d-42f3-ab0e-96a427fd4f80.png">

## Tasks

- [ ] re-design history widget to fit the bigger widget area.
- [ ] implement

## Designs

Please work in this design file
https://www.figma.com/file/eOalPm0jO9Uod5VL7bWqIQ/History-widget-re-design?node-id=0%3A1

Here is the rest of our designs, feel free to browse
https://www.figma.com/file/KHt6RPqitWphkuchA8vo0I/TOKEL-UI

**Comment by lenilsonjr** [comment]
Closed by @rannyeribaptist on #271
