### ISSUE TITLE
Create a new widget to show users's TKL address and users token address (pubkey)

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#268]
## Task

Create a new widget to show users TKL address and users token address (pubkey). This widget will replace the current history widget. The current history widget will move to the empty space where the graph widget was supposed to be.

Information about users address and pubkey is stored in redux-rematch store in model account.

### Sample design

Feel free to modify the design below if you think of any improvements. 

Clicking on button "Show" will open the same modal as is currently opened on clicking button "Receive" on the Transfer modal. The Modal title should be either: "TKL address" or "Token/NFT address (pubkey)"

![AddressWidget](https://user-images.githubusercontent.com/2395326/160048688-75ede432-5347-43c5-b39b-cbef5f84062b.png)

#### Modal on button Show

The modal is already created, so only need to hook it to a different button. Currently it is hooked to button Receive, we want it to be hooked to the button Show on the new widget. Transfer widget will change as part of another task and the Receive button won't be there anymore.

Click Receive to open Modal
<img width="1235" alt="Screenshot 2022-03-25 at 11 42 36" src="https://user-images.githubusercontent.com/2395326/160050071-a6544fd8-6f61-4d0e-8962-ddbae1688f44.png">

<img width="1096" alt="Screenshot 2022-03-25 at 11 42 24" src="https://user-images.githubusercontent.com/2395326/160050102-f4a3d92a-e668-4c0b-9291-94df4e8a43c6.png">

**Comment by lenilsonjr** [comment]
Closed by @rannyeribaptist on #271
