### ISSUE TITLE
Test the time lock binary

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_dapp#272]
#### TKL address no locked transactions

1. Open an address with TKL (without locked transactions)
2. Transfer widget is supposed to show the spendable amount and no locked amount. Spendable = Total TKL.

<img width="418" alt="TransferWidget-noLock" src="https://user-images.githubusercontent.com/2395326/162142072-df7d406e-a72d-41a5-b062-1cfbdb8a3ed5.png">

#### TKL address with locked transactions (still locked)

1. Send a locked transaction to your TKL address
2. Transfer widget is supposed to show spendable and locked amounts. Spendable + locked = total (top left on the dashboard). 3. Check if the date of the locked funds is correct.

<img width="418" alt="TransferWidgetLock" src="https://user-images.githubusercontent.com/2395326/162142405-c449e09d-09c0-49dc-b6da-54d99b555fcf.png">

#### TKL address with locked transactions (unlocked)

1. Wait until the transaction unlocks
2. Transfer widget is supposed to show Spendable TKL only. Spendable = Total TKL.
3. You are able to spend the TKL.

<img width="418" alt="TransferWidget-noLock" src="https://user-images.githubusercontent.com/2395326/162142072-df7d406e-a72d-41a5-b062-1cfbdb8a3ed5.png">

**Comment by dimxy** [comment]
tested okay: send locked coins from CLI to my wallet and saw them in the dapp GUI as 'locked'. After lock-time had passed the coins became unlocked

**Comment by jorian** [comment]
But did you send them away after that? Because that's not working for me, straight after it unlocks.

**Comment by dimxy** [comment]
> But did you send them away after that? Because that's not working for me, straight after it unlocks.

i did not. Will do

**Comment by jorian** [comment]
See #275 for relevant issue.

**Comment by dimxy** [comment]
nspv-js lib needs fixing...

**Comment by dimxy** [comment]
I fixed nspv-js for correct tx.nLockTime and tx.vin[].sequence to allow CLTV spending
please update it from https://github.com/dimxy/bitgo-komodo-cc-lib/tree/tokel

**Comment by jorian** [comment]
@piggydoughnut I assume this change needs to be integrated first?

**Comment by piggydoughnut** [comment]
everything integrated and released 🆗  check latest release
