### ISSUE TITLE
Transaction history should differentiate between transaction types

### ISSUE THREAD

**Issue by lenilsonjr** [TokelPlatform/tokel_dapp#273]
Right now, the dApp transaction history only shows txs as either deposits or withdrawals. Would be interesting to expand that to note in transactions what they actually are (ex.: token created, marketplace transaction, tx change, interacted with specific CC, etc)

<img width="801" alt="CleanShot 2022-04-18 at 11 43 12@2x" src="https://user-images.githubusercontent.com/3309021/163797465-fa68296f-c302-4abe-b626-c201ce314ee1.png">

**Comment by NutellaLicka** [comment]
Issue tracked here:
https://github.com/TokelPlatform/tokel_dapp/issues/196

Closing this one so we keep it in one place.
