### ISSUE TITLE
Transaction amount incorrect when using CLTV

### ISSUE THREAD

**Issue by jorian** [TokelPlatform/tokel_dapp#276]
In the transaction detail modal it shows the total value of the transaction, while only the received TKL should be the amount.

![image](https://user-images.githubusercontent.com/10341677/164396852-c60a335c-5bf1-47d3-ac69-0bf78153c8be.png)

## Operation System

Ubuntu 20
TKLTEST2

## Expected Behavior

To see 1 TKL as the amount.

## Current Behavior

I see the total value of the transaction, 43 TKL in this case, where 42 TKL is being sent as change which the wallet has no control over.

These amounts persist for at least 45 minutes, it doesn't resolve itself after some confirmations.

Transaction details: http://explorer.komodoplatform.com:20000/tx/784eafa03ccddb458e89b212efb9e263c1abf9e6f953717b03a2850e9c617cc5/TKLTEST2

The Transfer pane does show the correct, spendable amount:

![image](https://user-images.githubusercontent.com/10341677/164403830-ab1d4b9e-1f35-41c8-8ed6-b09563c4505e.png)

## Steps to Reproduce

1. Send a timelocked transaction to a new, empty wallet. (`sendtoaddress <address> <amount> "" "" false "" <epochtime>`)

2. Click on the transaction details in the History pane

3.

4.

## Possible Solution (Not obligatory)

Only show the amount that belongs to the address that is owned by the seedphrase.

**Comment by piggydoughnut** [comment]
provide links to transactions please

**Comment by piggydoughnut** [comment]
@jorian  I have a question
>  I see the total value of the transaction, 43 TKL in this case, where 42 TKL is being sent as change which the wallet has no control over.

I am looking at http://explorer.komodoplatform.com:20000/tx/784eafa03ccddb458e89b212efb9e263c1abf9e6f953717b03a2850e9c617cc5/TKLTEST2 and I see that 42.27535  is the amount that was sent, it is not change since it is going to a different address. So the amount left in the wallet should be 1 TKL, just like the app says. Please correct me if I am missing something.

I do agree that transaction detail does not show the correct amount for this transaction and I think I know why.

**Comment by jorian** [comment]
That the 42.27535 TKL is going back to a different address doesn't mean it's not change. It's the default behavior when working with the CLI, to preserve privacy. 
Also, to reiterate, the 1 TKL was sent from the CLI to the dapp address as a timelocked transaction, nothing was sent from the dapp.
I wouldn't expect to see the 43 TKL there because the dapp address never had 43 TKL; the 43 TKL is the sum of both outputs of the timelocked transaction I did (42 change, 1 timelocked to dapp address). Unless it is desired to have this behaviour, though I don't see the 'value' of that.

**Comment by piggydoughnut** [comment]
Oooh I think I maybe starting tp understand the whole change thing 😄

**Comment by piggydoughnut** [comment]
Resolved this by adjusting parsing algorithm in nspv-js, see https://github.com/TokelPlatform/nspv-js/pull/22
