### ISSUE TITLE
Failure of complete NFT url uploading

### ISSUE THREAD

**Issue by daybreak957** [TokelPlatform/tokel_dapp#280]
When I open Tokel wallets versions 1.2.1 and 1.2.2 with my seed phrase I am able to view two NFTs and one Early Adopter Token.  When I click on the Token I can see the moving image within the wallet. If I click on the url it opens in my browser.

However, when I click on either NFT I can see all the information but there is no image in the wallet.  When I click on the url the browser opens but to an error page.  I first became aware of this problem when Eureka John sent me my first NFT about a month ago from his interview with NutellaLicka.  We messed with it awhile but we're never able to get it open.  Even after waiting a month, it never resolved.

I recently won a Tokel NFT from Tokel Talk and was really excited to see if I'd gotten a purple spaceship.  Unfortunately, again there was no image in the wallet and the url was broken.  After looking closely at the working Token url I rewrote the address in the browser mimicking the working address but with the spaceship identifier and viola! I got the purple spaceship! So happy.

So, what's happening between the creation of the NFT and the receiving of the NFT to the PubKey?  I believe that if this glitch is corrected not only will I be able to see my NFTs in the wallet but, we will all be able to see them in the Discord creation feed.  But what do I know?!

Here are the steps to recreate the problem.

This is what I see when I open either wallet 👇
![image](https://user-images.githubusercontent.com/91099672/165435273-7801dffd-4d27-4ddd-a1f1-6f5d2d1dabe0.png)

The address reads:  ipfs://bafybeiaiftrw......

If the full url is typed into the browser it works just fine:

https://ipfs.io/ipfs/bafybeiaiftrw4ao2ziegup4ncjff7oimn5fzs4bchscwjnbhxkmfiwkceu

But even that is not technically correct, even if it works to add https://ipfs.io/ipfs/ (dropping the colon and second forward slash).

I went and looked up #43 in the creation-feed and what is listed there is a different url that also works.

https://infura-ipfs.io/ipfs/bafybeiaiftrw4ao2ziegup4ncjff7oimn5fzs4bchscwjnbhxkmfiwkceu

So why does the url change when the NFT is sent to a different wallet?
The abbreviation isn't a functioning link. I hope figuring this out helps you make an even better wallet. I'm really happy with my purple spaceship otherwise.

Daybreak

PS. I have not been able to open the other NFT from John no matter what I type into the browser.
Peace~ Love~ Freedom~

**Comment by lenilsonjr** [comment]
The image not loading is tracked on #238. About the link, this Discord message might clarify it: https://discord.com/channels/774497890025472010/781788743228325898/968806874604507156

I have create a new issue on #282 to improve the UX of opening IPFS links on browser gateways when the dApp fails to load media.

I'll close this for now, let me know if you have any other questions or issues. Thanks for engaging and helping improve the dApp! 🙌

**Comment by lenilsonjr** [comment]
@rannyeribaptist Actually, it's worth investigating in this specific case:

- if dapp is loading externalMedia.html iframe properly
- if extractIPFSHash function is extracting the hash properly

If you don't mind, creating a test token that contains the same IPFS link `ipfs://` as the screenshot attached might show if there's any issues with our hash parsing setup.

Please check this along #282

**Comment by daybreak957** [comment]
Thanks for the follow-up. I've learned a lot about how GitHub works following the links. Don't overlook #255 as it was reviewed but, not solved yet. Have a great day!
