### ISSUE TITLE
Getting transactions bug

### ISSUE THREAD

**Issue by GingerDesigne** [TokelPlatform/tokel_dapp#298]
## Operation System

Windows 10 - Latest Build

## Expected Behavior

dApp should have functioned properly.

## Current Behavior

Installed the latest version of the dApp. Entered my seed key in and there was nothing on the dApp screen, no $TKL balance nor NFTs. Then the dApp screen turned into 'getting transactions' but it has been more than 17 hours and the process is still ongoing.

## Steps to Reproduce

1. Opening the dApp

2. Entering seed key

3. dApp stands idle for a few minutes -it also doesn't show any $TKL balance nor NFTs at this stage-

4. Then turns into 'Getting transactions' screen and it keep doing so

## Possible Solution (Not obligatory)

Maybe some internal problems with the nodes?
![dApp](https://user-images.githubusercontent.com/94997323/177387585-40bbcabc-1abb-4e64-b34c-3b23bf1b4a7b.PNG)

**Comment by NutellaLicka** [comment]
I believe this has been fixed in the latest release and with updated blockchain nodes. @GingerDesigne please confirm whether you're still getting this issue?

**Comment by GingerDesigne** [comment]
Hello @NutellaLicka 

Just checked it with the latest build of the dApp and it looks perfectly smooth now. No lagging, no _getting transactions_ error ever. My thanks.
