### ISSUE TITLE
Ubuntu 22.04 - GPU process isn't usable. Goodbye. Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by bobpepers** [TokelPlatform/tokel_dapp#301]
## Operation System

Ubuntu 22.04 jammy 

## Expected Behavior

AppImage should run

## Current Behavior
AppImage Does not Run and closes with a fatal error
```
[476959:0803/145917.418155:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Illegal instruction (core dumped)
```
![image](https://user-images.githubusercontent.com/40283955/182788860-1c9f0c8d-0feb-4aee-93d5-ea9dbea566fd.png)

## Steps to Reproduce

1. Install Ubuntu 22.04 Jammy
2. Download tokel_dapp's AppImage
3. Set the permission to allow the AppImage to run
4. Run it

## Possible Solution (Not obligatory)

After searching for the issue, it's suggested that the error is mostly caused to electron apps that use old electron dependencies (out-of-date electron dependencies)
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/47
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/48

So updating the electron dependencies and fixing the breaking changes that come with updating them should solve the issue
![image](https://user-images.githubusercontent.com/40283955/182790263-6a5118a7-c4ce-43ef-b222-06ea43956a89.png)

(Bring all the other dependencies up to date to avoid any additional issues)

**Comment by bobpepers** [comment]
forgot to mention, the workaround for users who run into this issue until fixed is appending `--no-sandbox` to appImage launch

**Comment by TheComputerGenie** [comment]
Should be fixed with current update schedule.
If not fixed in next release, please reopen.
